import snowAngel from './img/snow-angel.svg'
import snowMan from './img/make-snowman.svg'
import boy from './img/boy.svg'
import boy2 from './img/boy-2.svg'
import girl from './img/girl.svg'
import girl2 from './img/girl-2.svg'
import letter1 from './img/letters/letter_1.jpg'
import letter2 from './img/letters/letter_2.jpeg'
import letter3 from './img/letters/letter_3.jpeg'
import letter4 from './img/letters/letter_4.jpeg'
import letter5 from './img/letters/letter_5.jpeg'
import letter6 from './img/letters/letter_6.jpeg'
import letter7 from './img/letters/letter_7.jpeg'
import letter8 from './img/letters/letter_8.jpeg'
import letter9 from './img/letters/letter_9.jpeg'
import letter10 from './img/letters/letter_10.jpeg'
import letter11 from './img/letters/letter_11.jpeg'
import letter12 from './img/letters/letter_12.jpeg'
import letter13 from './img/letters/letter_13.jpeg'
import letter14 from './img/letters/letter_14.jpeg'
import letter15 from './img/letters/letter_15.jpeg'
import letter16 from './img/letters/letter_16.jpeg'


export const data = [
    { id: 1, status: 'in-progress', image: snowAngel, label: 'В процессе', percantage: 0,
    name: 'Дима',
    age: '16 лет',
    like: 'заниматься спортом', 
    skill: 'заниматься рементом',
    wish: 'отлично выполнять ремонт в доме',
    action: 'Помогал выполнять хозяйственные дела в центре', 
    dream: 'шуроповертe для ремонта помещений',
    letter: letter1,
     title: 'Дима, 16 лет',
     showLink: 'show',
     showBtn: 'show'},
    { id: 2, status: 'in-progress', image: snowMan, label: 'В процессе',percantage: 0,
     title: 'Богдан, 7 лет',
    name: 'Богдан',
    age: '7 лет',
    like: 'музыка и петь', 
    skill: 'рисовать',
    wish: 'отлично выполнять ремонт в доме',
    action: 'убирал комнаты и кладовые своим веником', 
    letter: letter2,
    dream: 'машину на управлении',
    showLink: 'show',
    showBtn: 'show'},
    { id: 3, status: 'in-progress', image: boy, label: 'В процессе',percantage: 0,
    title: 'Максим, 16 лет', 
    name: 'Максим',
    age: '16 лет',
    like: 'играть в футбол', 
    skill: 'собирать из конструктора модели',
    wish: 'хорошо читать и писать',
    action: 'помогать младшему брату Илье, убирать комнату', 
    letter: letter3,
    dream: 'музыкальной колонке JBL',
    showLink: 'show',
    showBtn: 'show'},
    { id: 4, status: 'in-progress', image: girl, label: 'В процессе',percantage: 0,
     title: 'Виолетта, 14 лет',
     name: 'Виолетта',
    age: '14 лет',
    like: 'Мне нравится заниматься спортом', 
    skill: 'Хорошо рисовать',
    wish: 'Хорошо относиться к людям',
    action: 'Не пропускаю уроки в школе. Ухаживаю за своими вещами. Уважаю старших', 
    letter: letter4,
    dream: 'смарт часах и спортивном костюме (размер 46)', showLink: 'show',
    showBtn: 'show'},
    { id: 5, status: 'in-progress', image: boy2, label: 'В процессе',percantage: 0,
     title: 'Саша, 9 лет',
     name: 'Саша',
    age: '9 лет',
    like: 'играть с друзьями', 
    skill: 'складывать пазлы',
    wish: 'писать и читать',
    action: 'помогаю убирать в комнате', 
    letter: letter5,
    dream: 'машине на радиоуправлении', showLink: 'show',
    showBtn: 'show'},
    { id: 6, status: 'in-progress', image: snowAngel, label: 'В процессе',percantage: 0,
     title: 'Миша, 14 лет',
     name: 'Миша',
     age: '14 лет',
     like: 'заниматься спортом', 
     skill: 'Хорошо играть в футбол',
     wish: 'Хорошо играть в баскетбол',
     action: 'помагал братьям, помогаю тренеру на занятиях', 
     letter: letter6,
       dream: 'музыкальной колонке JBL', showLink: 'show',
    showBtn: 'show'},
    { id: 7, status: 'in-progress', image: boy, label: 'В процессе',percantage: 0,
     title: 'Ваня, 12 лет',
     name: 'Ваня',
     age: '12 лет',
     like: 'заниматься спортом', 
     skill: 'играть в футбол',
     wish: 'хорошо научиться быстро бегать и стать умным',
     action: 'перенес пожилой женщине тяжелую сумку, помогла маме по хозяйству, по уборке огорода', 
     letter: letter7,
       dream: 'машине на пульте управления', showLink: 'show',
    showBtn: 'show'},
    { id: 8, status: 'in-progress', image: girl2, label: 'В процессе',percantage: 0,
     title: 'Лера, 7 лет', 
     name: 'Лера',
    age: '7 лет',
    like: 'рисовать', 
    skill: 'собирать пазлы, читать книги',
    wish: 'мыть посуду, кататься на велосипеде',
    action: 'хорошо учусь и хорошо себя веду', 
    letter: letter8, 
     dream: 'куколку с одеждой', showLink: 'show',
    showBtn: 'show'},
    { id: 9, status: 'in-progress', image: girl, label: 'В процессе', percantage: 0,
    title: 'Катя, 4 года', 
    name: 'Катя',
    age: '4 года',
    like: 'танцевать в красивом платье', 
    skill: 'играть с куклами',
    wish: 'хорошо рисовать',
    action: 'помогаю убирать игрушки, с удовольствием занимаюсь с воспитателем', 
    letter: letter9,
    dream: 'большой кукле, чтобы ее можно было кормить, ухаживать, одевать. Хочу чтобы она была моими другом', showLink: 'show',
    showBtn: 'show'},
    { id: 10, status: 'in-progress', image: snowMan, label: 'В процессе', percantage: 0,
    title: 'Данил, 6 лет', 
    name: 'Данил',
    age: '6 лет',
    like: 'читать', 
    skill: 'писать буквы',
    wish: 'делать красивые поделки',
    action: 'помогал убирать комнату', 
    letter: letter10,
    dream: 'машине на радиоуправлении', showLink: 'show',
    showBtn: 'show'},
    { id: 11, status: 'in-progress', image: girl, label: 'В процессе', percantage: 0,
    title: 'Диана, 6 лет', 
    name: 'Диана',
    age: '6 лет',
    like: 'играть', 
    skill: 'петь, танцевать',
    wish: 'хорошо читать',
    action: 'помогаю младшей сестре', 
    letter: letter11,
    dream: 'детской косметике и большой кукле', showLink: 'show',
    showBtn: 'show'},
    { id: 12, status: 'in-progress', image: boy2, label: 'В процессе', percantage: 0,
    title: 'Илья, 3 года', 
    name: 'Илья',
    age: '3 года',
    like: 'играть с машинками', 
    skill: 'играть',
    wish: '',
    action: 'здороваюсь со всеми, говорю спасибо, сам одеваюсь', 
    letter: letter12,
    dream: 'большой машине, чтобы в ней можно было возить кубики, катать мишек', showLink: 'show',
    showBtn: 'show'},
    { id: 13, status: 'in-progress', image: snowAngel, label: 'В процессе', percantage: 0,
    title: 'Дима, 5 лет', 
    name: 'Дима',
    age: '5 лет',
    like: 'играть машинками', 
    skill: 'делать зарядку',
    wish: 'читать и писать',
    action: 'покупаю продукты', 
    letter: letter13, 
    dream: 'игрушечном тракторе с прицепом', showLink: 'show',
    showBtn: 'show'},
    { id: 14, status: 'in-progress', image: girl2, label: 'В процессе', percantage: 0,
    title: 'Наташа, 6 лет', 
    name: 'Наташа',
    age: '6 лет',
    like: 'конфеты', 
    skill: 'буквы писать',
    wish: 'рисовать',
    action: 'училась читать и писать', 
    letter: letter14,
    dream: 'конфетах и большой кукле', showLink: 'show',
    showBtn: 'show'},
    { id: 15, status: 'in-progress', image: boy, label: 'В процессе', percantage: 0, 
    title: 'Руслан, 10 лет', 
    name: 'Руслан',
    age: '10 лет',
    like: 'рисовать', 
    skill: 'хорошо играть в футбол',
    wish: 'Собирать конструктор LEGO',
    action: 'стал получать хорошие оценки', 
    letter: letter15, 
    dream: 'большом конструкторе', showLink: 'show',
    showBtn: 'show'},
    { id: 16, status: 'in-progress', image: girl, label: 'В процессе', percantage: 0,
    title: 'Рита, 11 лет', 
    name: 'Рита',
    age: '11 лет',
    like: 'играть', 
    skill: 'петь',
    wish: 'убирать комнату',
    action: 'помогать всем', 
    letter: letter16, 
    dream: 'рюкзачке для девочек', 
    showLink: 'show',
    showBtn: 'show'},
  ]